// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWarsDatabank.FFG.Data;

namespace StarWarsDatabank.FFG.Data.Migrations
{
    [DbContext(typeof(FFGDatabankContext))]
    partial class FFGDatabankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarWarsDatabank.Framework.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameVersionId")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.HasIndex("GameVersionId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("StarWarsDatabank.Framework.GameVersion", b =>
                {
                    b.Property<int>("GameVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("GameVersionId");

                    b.ToTable("GameVersions");
                });

            modelBuilder.Entity("StarWarsDatabank.Framework.Book", b =>
                {
                    b.HasOne("StarWarsDatabank.Framework.GameVersion", "RPG")
                        .WithMany()
                        .HasForeignKey("GameVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RPG");
                });
#pragma warning restore 612, 618
        }
    }
}
